# Generated by Django 3.2 on 2023-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admini', 'Администратор')], default='user', max_length=15, verbose_name='Роль пользователя'),
        ),
    ]
