# Generated by Django 3.2 on 2023-02-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_titlegenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
