# Generated by Django 3.2 on 2023-02-04 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230203_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='pub_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата публикации'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
